# Algo de recommandation de films

## Cas pratique : implémenter un algorithme de recommandation de film en python avec le dataset movies.csv :
**Dataset : https://drive.google.com/drive/u/0/folders/1uT07y43Ik4nmG8jnN1Gv6ozeZhWEIhNb**

- Question 1 : importer Pandas, Numpy, CountVectorizer() et cosine_similarity() et le dataset
- Question 2 : Faire une fonction appelé combine_features() qui va combiner les features
['keywords','cast','genres','director'] dans un unique string
- Question 3 : Utiliser la fonction fillna() de Pandas pour remplir les NaN du dataset par des
string vide et créer une nouvelle colonne appelé “combined_features” en appliquant la
fonction combine_features() sur chaque ligne du dataset.
- Question 4 : Utiliser la fonction CountVectorizer() et afficher la matrice de comptage de la
nouvelle colonne combined_features.
- Question 5 : Utiliser la fonction cosine_similarity() sur la matrice de comptage définie à la
question précédente et créer une variable avec.
- Question 6 : Utiliser ces fonction afin de calculer le top 5 des films similaire au film Avatar
 - Indice 1 : utiliser la fonction get_index_from_title() sur le film demandé et utiliser ensuite la
variable définie à la question précédente.
 - Indice 2 : Trier la liste obtenue à l’aide du résultat de l’indice précédent.
 - Indice 3 : Faire une boucle sur la liste obtenue et stopper votre boucle à la 5eme itération

 -----------------------------------------------------------------------

### Question 1

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
#df = pd.read_csv('movies.csv')
df = pd.read_csv("https://raw.githubusercontent.com/BaptisteHurel/DeepLearning/main/NLP/movies.csv")

df.head()

index  ...           director
0      0  ...      James Cameron
1      1  ...     Gore Verbinski
2      2  ...         Sam Mendes
3      3  ...  Christopher Nolan
4      4  ...     Andrew Stanton

[5 rows x 24 columns]

### Question 2


In [ ]:
def combine_features(tab):
  tab = [str(item) for item in tab]
  return ' '.join(tab)

In [ ]:
combine_features(['keywords','cast','genres','director'])

'keywords cast genres director'

### Question 3

In [ ]:
df.isna().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [ ]:
df = df.fillna("")

In [ ]:
df.dtypes

index                     int64
budget                    int64
genres                   object
homepage                 object
id                        int64
keywords                 object
original_language        object
original_title           object
overview                 object
popularity              float64
production_companies     object
production_countries     object
release_date             object
revenue                   int64
runtime                  object
spoken_languages         object
status                   object
tagline                  object
title                    object
vote_average            float64
vote_count                int64
cast                     object
crew                     object
director                 object
dtype: object

In [ ]:
for i, row in df.iterrows():
  df.loc[i, "combine_features"] = combine_features(row)

In [ ]:
df.head()

index  ...                                   combine_features
0      0  ...  0 237000000 Action Adventure Fantasy Science F...
1      1  ...  1 300000000 Adventure Fantasy Action http://di...
2      2  ...  2 245000000 Action Adventure Crime http://www....
3      3  ...  3 250000000 Action Crime Drama Thriller http:/...
4      4  ...  4 260000000 Action Adventure Science Fiction h...

[5 rows x 25 columns]

### Question 4


In [167]:
count_vect = CountVectorizer()
count_matrix = count_vect.fit_transform(df.combine_features)

print(count_vect.get_feature_names())
print(count_matrix.toarray())

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


### Question 5


In [168]:
similarity_scores = cosine_similarity(count_matrix)
print(similarity_scores)

[[1.         0.93918141 0.98638069 ... 0.84596317 0.40925216 0.64632696]
 [0.93918141 1.         0.94532537 ... 0.89744807 0.4637389  0.69103533]
 [0.98638069 0.94532537 1.         ... 0.85953457 0.41825575 0.65536215]
 ...
 [0.84596317 0.89744807 0.85953457 ... 1.         0.4859271  0.683106  ]
 [0.40925216 0.4637389  0.41825575 ... 0.4859271  1.         0.4526639 ]
 [0.64632696 0.69103533 0.65536215 ... 0.683106   0.4526639  1.        ]]


### Question 6

In [179]:
def get_title_from_index(index):
    return df[df.index == index]["title"].values[0]
def get_index_from_title(title):
    return df[df.title == title]["index"].values[0]

In [180]:
movie = "Avatar"
movie_index = get_index_from_title(movie)

In [183]:
similar_movies = list(enumerate(similarity_scores[movie_index]))

In [185]:
sorted_similar_movies = sorted(similar_movies,key=lambda x:x[1],reverse=True)[1:]

In [187]:
x=0
for element in sorted_similar_movies:
    print(get_title_from_index(element[0]))
    x=x+1
    if x>5:
        break

The Hunger Games: Mockingjay - Part 1
Ender's Game
Exodus: Gods and Kings
The Avengers
Cloud Atlas
The Day After Tomorrow
